//
// Created by Oscar on 27/1/2026.
//

#ifndef PROYECTOPROGRAIAARONDU_CONTROLADORA_H
#define PROYECTOPROGRAIAARONDU_CONTROLADORA_H


class Controladora {
};


#endif //PROYECTOPROGRAIAARONDU_CONTROLADORA_H